<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
    <WebView2PackagePath>$(NuGetPackageRoot)microsoft.web.webview2\1.0.4078.44</WebView2PackagePath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DalamudActCompat.Protocol\DalamudActCompat.Protocol.csproj" />
    <PackageDownload Include="Microsoft.Web.WebView2" Version="[1.0.4078.44]" />
    <ProjectReference Include="..\..\vendor\IINACT\IINACT\IINACT.csproj" />
    <PackageReference Include="System.Formats.Nrbf" Version="10.0.10" GeneratePathProperty="true" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.10" />
    <Reference Include="Mono.Cecil">
      <HintPath>$(DalamudLibPath)Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>$(WebView2PackagePath)\lib_manual\netcoreapp3.0\Microsoft.Web.WebView2.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.WinForms">
      <HintPath>$(WebView2PackagePath)\lib_manual\netcoreapp3.0\Microsoft.Web.WebView2.WinForms.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Dalamud">
      <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Lumina">
      <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FFXIVClientStructs">
      <HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="InteropGenerator.Runtime">
      <HintPath>$(DalamudLibPath)InteropGenerator.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(DalamudLibPath)Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin">
      <HintPath>..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Common">
      <HintPath>..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Common.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Config">
      <HintPath>..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Config.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Logfile">
      <HintPath>..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Logfile.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Memory">
      <HintPath>..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Memory.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Network">
      <HintPath>..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Network.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Parse">
      <HintPath>..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Parse.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Resource">
      <HintPath>..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Resource.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(WebView2PackagePath)\runtimes\win-x64\native\WebView2Loader.dll"
             Link="WebView2Loader.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="$(PkgSystem_Formats_Nrbf)\lib\net10.0\System.Formats.Nrbf.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Common.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Config.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Logfile.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Memory.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Network.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Parse.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\vendor\IINACT\external_dependencies\FFXIV_ACT_Plugin.Resource.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
